### ISSUE TITLE
Make this into a GitBook

### ISSUE THREAD

**Issue by ruckustboom** [Froussios/Intro-To-RxJava#22]
Just a suggestion, but you may want to consider making this into a [GitBook](https://www.gitbook.com/). It's just more pleasant for reading.

**Comment by Froussios** [comment]
I don't like the kind of permissions that GitBook requires to perform their services. I also think that the value that they would add to this project is small. For those reasons, I will not create a GitBook.

If there is a change in the GitHub API or the way that GitBook offer their service, I may revisit this decision.

If you disagree, you always have the option to fork the project and create a book yourself.

**Comment by t-boom** [comment]
Good to know. I don't have much experience with GitBook (outside of reading), so I'll have to look into the permissions.

**Comment by piotrek1543** [comment]
@Froussios any changes? I mean, are you going to publish or made a more digital version version. It would be wonderful to have it in pdf/mobi/epub.
