### ISSUE TITLE
Example with 'sequenceEqual' operator is wrong

### ISSUE THREAD

**Issue by piotrek1543** [Froussios/Intro-To-RxJava#30]
Hi, 

going through your excellent tutorial I I've already noticed that I cannot write a function like this:
          
    Observable.sequenceEqual(strings, ints, (s,i) -> s.equals(i.toString()))
    //Observable.sequenceEqual(strings, ints)
        .subscribe(
            v -> System.out.println(v),
            e -> System.out.println("Error: " + e),
            () -> System.out.println("Completed")
        );

The working version should be like this:

    Subscription sequenceEqual = Observable.sequenceEqual(
            just1, just2, (s, i) -> s.equals(just1.toString())).subscribe();

where declarations of `just1` and `just2' variables:

     Observable<Integer> just1 = Observable.just(1, 2, 3);
     Observable<String> just2 = Observable.just("1", "2", "3");

Did you forgot to declare a variable or it changed with newer version of RxJava?

I'm using this dependencies:

    compile 'io.reactivex:rxjava:1.1.1'
    compile 'io.reactivex:rxandroid:1.1.0'

Cheers

**Comment by piotrek1543** [comment]
The same situation with 'reduce' example

**Comment by piotrek1543** [comment]
If you don't mind, I can do a pull request with desired changes, just let me know.

**Comment by piotrek1543** [comment]
@Froussios I noticed that you're fixed typo, could you also change this? Thanks in advance

**Comment by Froussios** [comment]
I don't understand what the difference is in the changed example. Can you elaborate?

**Comment by Froussios** [comment]
Why not use `strings` and `ints` as they are declared in the example?
The associated .java file also seems to work without problem.

**Comment by piotrek1543** [comment]
@Froussios Well, the problem was that I couldn't use

            Observable.sequenceEqual(strings, ints, (s,i) -> s.equals(i.toString()))

without declaration of `Subscription` like:

            Subscription sequenceEqual = Observable.sequenceEqual(...)

Every time I tried to compile it, it returned an error. As you may noticed I used version `1.1.1`

Now I changed dependency to `compile 'io.reactivex:rxjava:1.2.1'` and it works without this disused decraration I mean:

            Subscription sequenceEqual = ...

Strange, maybe there was another 'typo' issue or this version of lib was corrupted.

Nevermind. Now it works fine.
Thanks for response.
